load("@rules_cc//cc:defs.bzl", "cc_binary", )


cc_binary(
    name = "test-01-load",
    srcs = ["test-01-load.cpp"], 
    deps = [
        "//src:chip8",
    ],
)

cc_binary(
    name = "test-02-funcMap",
    srcs = ["test-02-funcMap.cpp"], 
    deps = [
        "//src:chip8",
    ],
)
